### PR TITLE
Remove Java 22 support / Add Java 23 support

### PR DESCRIPTION
**Pull request by anthonydahanne**
the usual non LTS update: we remove the previous, replacing it with the latest!

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by anthonydahanne** [comment]
CAREFUL!!!
it seems like Bellsoft NIK 23 is not available yet

**Comment by patpatpat123** [comment]
Adding myself here. Hope this will get released!

Thanks

**Comment by patpatpat123** [comment]
This is the current log I am getting, just FYI:


```
       [INFO]  > Running creator
[INFO]     [creator]     ===> ANALYZING
[INFO]     [creator]     Image with name "docker.io/library/graaal:0.0.1-SNAPSHOT" not found
[INFO]     [creator]     ===> DETECTING
[INFO]     [creator]     target distro name/version labels not found, reading /etc/os-release file
[INFO]     [creator]     6 of 15 buildpacks participating
[INFO]     [creator]     paketo-buildpacks/ca-certificates   3.8.4
[INFO]     [creator]     paketo-buildpacks/bellsoft-liberica 10.8.2
[INFO]     [creator]     paketo-buildpacks/syft              1.47.2
[INFO]     [creator]     paketo-buildpacks/executable-jar    6.11.0
[INFO]     [creator]     paketo-buildpacks/spring-boot       5.31.0
[INFO]     [creator]     paketo-buildpacks/native-image      5.14.2
[INFO]     [creator]     ===> RESTORING
[INFO]     [creator]     ===> BUILDING
[INFO]     [creator]     target distro name/version labels not found, reading /etc/os-release file
[INFO]     [creator]     
[INFO]     [creator]     Paketo Buildpack for CA Certificates 3.8.4
[INFO]     [creator]       https://github.com/paketo-buildpacks/ca-certificates
[INFO]     [creator]       Build Configuration:
[INFO]     [creator]         $BP_EMBED_CERTS                    false  Embed certificates into the image
[INFO]     [creator]         $BP_ENABLE_RUNTIME_CERT_BINDING    true   Deprecated: Enable/disable certificate helper layer to add certs at runtime
[INFO]     [creator]         $BP_RUNTIME_CERT_BINDING_DISABLED  false  Disable certificate helper layer to add certs at runtime
[INFO]     [creator]       Launch Helper: Contributing to layer
[INFO]     [creator]         Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper
[INFO]     [creator]     
[INFO]     [creator]     Paketo Buildpack for BellSoft Liberica 10.8.2
[INFO]     [creator]       https://github.com/paketo-buildpacks/bellsoft-liberica
[INFO]     [creator]       Build Configuration:
[INFO]     [creator]         $BP_JVM_JLINK_ARGS           --no-man-pages --no-header-files --strip-debug --compress=1  configure custom link arguments (--output must be omitted)
[INFO]     [creator]         $BP_JVM_JLINK_ENABLED        false                                                        enables running jlink tool to generate custom JRE
[INFO]     [creator]         $BP_JVM_TYPE                 JRE                                                          the JVM type - JDK or JRE
[INFO]     [creator]         $BP_JVM_VERSION              17                                                           the Java version
[INFO]     [creator]       Launch Configuration:
[INFO]     [creator]         $BPL_DEBUG_ENABLED           false                                                        enables Java remote debugging support
[INFO]     [creator]         $BPL_DEBUG_PORT              8000                                                         configure the remote debugging port
[INFO]     [creator]         $BPL_DEBUG_SUSPEND           false                                                        configure whether to suspend execution until a debugger has attached
[INFO]     [creator]         $BPL_HEAP_DUMP_PATH                                                                       write heap dumps on error to this path
[INFO]     [creator]         $BPL_JAVA_NMT_ENABLED        true                                                         enables Java Native Memory Tracking (NMT)
[INFO]     [creator]         $BPL_JAVA_NMT_LEVEL          summary                                                      configure level of NMT, summary or detail
[INFO]     [creator]         $BPL_JFR_ARGS                                                                             configure custom Java Flight Recording (JFR) arguments
[INFO]     [creator]         $BPL_JFR_ENABLED             false                                                        enables Java Flight Recording (JFR)
[INFO]     [creator]         $BPL_JMX_ENABLED             false                                                        enables Java Management Extensions (JMX)
[INFO]     [creator]         $BPL_JMX_PORT                5000                                                         configure the JMX port
[INFO]     [creator]         $BPL_JVM_HEAD_ROOM           0                                                            the headroom in memory calculation
[INFO]     [creator]         $BPL_JVM_LOADED_CLASS_COUNT  35% of classes                                               the number of loaded classes in memory calculation
[INFO]     [creator]         $BPL_JVM_THREAD_COUNT        250                                                          the number of threads in memory calculation
[INFO]     [creator]         $JAVA_TOOL_OPTIONS                                                                        the JVM launch flags
[INFO]     [creator]         Using Java version 23 extracted from MANIFEST.MF
[INFO]     [creator]     
[INFO]     [creator]     Paketo Buildpack for BellSoft Liberica 10.8.2
[INFO]     [creator]       unable to find dependency
[INFO]     [creator]       no valid dependencies for native-image-svm, 23, and io.buildpacks.stacks.jammy.tiny in [(jdk, 8.0.422, [*]) (jre, 8.0.422, [*]) (jdk, 11.0.24, [*]) (jre, 11.0.24, [*]) (native-image-svm, 11.0.22, [*]) (jdk, 17.0.12, [*]) (jre, 17.0.12, [*]) (native-image-svm, 17.0.11, [*]) (jdk, 21.0.4, [*]) (jre, 21.0.4, [*]) (native-image-svm, 22.0.1, [*]) (jdk, 22.0.2, [*]) (jre, 22.0.2, [*]) (native-image-svm, 21.0.3, [*]) (jdk, 8.0.422, [*]) (jre, 8.0.422, [*]) (jdk, 11.0.24, [*]) (jre, 11.0.24, [*]) (native-image-svm, 11.0.22, [*]) (jdk, 17.0.12, [*]) (jre, 17.0.12, [*]) (native-image-svm, 17.0.11, [*]) (jdk, 21.0.4, [*]) (jre, 21.0.4, [*]) (native-image-svm, 21.0.3, [*]) (jdk, 22.0.2, [*]) (jre, 22.0.2, [*]) (native-image-svm, 22.0.1, [*])]
[INFO]     [creator]     ERROR: failed to build: exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  44.935 s
[INFO] Finished at: 2024-09-20T10:48:52+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.4.0-M3:build-image (default-cli) on project graaal: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:3.4.0-M3:build-image failed: Builder lifecycle 'creator' failed with status code 51 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException


```

**Comment by anthonydahanne** [comment]
@dmikusa it's ready now, I've locally run all 6 java 23 combination for Bellsoft and updated the `buildpack.toml`

**Review by dmikusa — APPROVED** [review]

**Comment by patpatpat123** [comment]
Hello team, thank you for merging this! 
Just wondering if I may, when is the date that will be released?
(Or please let me know where can I find that info, maybe in some mailing list, online calendar, will be happy to learn)

**Pull request merged**
