### PR TITLE
Add ARM64 dependencies

### PR DESCRIPTION
**Pull request by dmikusa**
## Summary

Adds the JRE, JDK and NIK dependencies for ARM64.

This commit also adds update workflows to keep these dependencies up-to-date. This will require https://github.com/paketo-buildpacks/pipeline-builder/pull/1348 to be merged first, because the workflows for ARM64 need to be able to pass the arch through to the GH Action that checks for Bellsoft updates.

## Use Cases

Add ARM64!

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by dmikusa** [comment]
The helpful part of this approach is that we only need minor changes to the actions in pipeline builder. You can see how the change on https://github.com/paketo-buildpacks/pipeline-builder/pull/1348 are pretty small. The downside of this approach is that it causes us to need a lot more update workflows in the actual buildpack repo, see this PR which doubles the number of workflows.

I'm not totally concerned with that. It will cause more jobs to run, but I think this just emphasizes another reason why we don't want to have dependencies inside of the buildpacks.

If folks are concerned about that, we could do this differently, but it would be more complicated and more work. What we'd need to do is to modify pipeline builder's octo and the update dependency job template so that it can take in a list of architectures. When given a single architecture it would generate the same workflow it does now. When given a list, it would generate the same workflow, but it would repeat the part where it calls the actual action to check for the update and the part that actually updates the buildpack.toml. That way it would repeat the action within the workflow. The downside of this approach is that if one of those action update steps fails, then they all fail.

Personally, I'd prefer to stick with the present solution as it is simpler. If we need to go down the road of optimizing the number of workflows then we can do that later. Hopefully we will not need to.

**Comment by anthonydahanne** [comment]
TBH, I think it's totally fine the way it is; as soon as we get away from multiple deps thanks to the soon to come RFC adding `archs`, we'll update pipeline builder and remove those extra workflows and buildpacks dependencies entries.

**Comment by anthonydahanne** [comment]
so https://github.com/paketo-buildpacks/pipeline-builder/pull/1348 is now merged; so... do we go and update bellsoft with this PR?!

maybe after the holiday season?

**Comment by anthonydahanne** [comment]
or when the tests pass 🙂

**Comment by dmikusa** [comment]
@anthonydahanne tests are passing now. I'm 👍 for moving.

**Review by anthonydahanne — APPROVED** [review]

**Pull request merged**
