### PR TITLE
Add java 18

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by TomBeckett** [comment]
@dmikusa-pivotal Anything we can do to merge this?

**Comment by dmikusa-pivotal** [comment]
I apologize for the delay. We have a CI issue that's popped up since adding Java 18 to a couple of the other buildpacks. We've been holding this back until we get that resolved. We're hoping to have it fixed shortly.

**Comment by dmikusa-pivotal** [comment]
@eddumelendez - Can you add a regex anchor for the pattern match for Java 8 to your PR?

[here](https://github.com/paketo-buildpacks/bellsoft-liberica/blob/main/.github/pipeline-descriptor.yml#L31) and [here](https://github.com/paketo-buildpacks/bellsoft-liberica/blob/main/.github/pipeline-descriptor.yml#L22).

It needs to be `^8\\.[\\d]+\\.[\\d]+` so that it doesn't match both Java 8 and Java 18.

**Comment by eddumelendez** [comment]
@dmikusa-pivotal done!

**Review by dmikusa-pivotal — APPROVED** [review]

**Comment by TomBeckett** [comment]
@dmikusa-pivotal Do you know when this may be released?

**Comment by dmikusa-pivotal** [comment]
I'm hoping to cut the release tomorrow. I have to coordinate some CI changes first.

**Pull request merged**
